---
title: "Kazuma_Oyama"
author: "Kazuma Oyama"
date: "11/28/2019"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
injury <- data.frame(read.csv("/Users/bigmountain0316/Desktop/2019/BST260-PROJECT/severeinjury.csv"))
injury_state <- injury %>% group_by(State) %>% summarise(number = n())
```

```{r}
injury_state_pop <- transform(injury_state, population = c(4898246,735720,55689,7275070,3026412,39747267,5770545,3567871,975033,711571,29087070,10627767,162742,1416589,1790182,12700381,6718616,3167997,2910931,4484047,4652581,1342097,6062917,6939373,10020472,5655925,2987895,6147861,1074532,1940919,3087025,1363852,8922547,2096034,19491339,10497741,760900,55144,11718568,3948950,4245901,12813969,3113659,1056738,5147111,892631,6833793,29087070,3221610,627180,106405,8571946,7666343,1791951,5832661,572381))
```
```{r}
ggplot(data = injury_state_pop, aes(x = population, y = number, label = State)) +　labs(title = "Relationship betweem population and the number of injury according to states ", x = "Population", y = "Number of injury") + geom_point()
```
```{r}
injury <- data.frame(read.csv("/Users/bigmountain0316/Desktop/2019/BST260-PROJECT/severeinjury.csv"))
pie_chart_hosp <- injury %>% select(Hospitalized)
```
```{r}
pie_chart_hosp1 <- injury %>% select(Hospitalized)
table(pie_chart_hosp)
pie_chart_hosp2 <- c(8881,36041)
pie(pie_chart_hosp2, radius=1, labels=c("Non-Hospitalzed 19.8%","Hospitalized 80.2%"), col=c("#0000FF","#FF8000"), main="Hospitalization Rate in All Injuries")
```

```{r}
pie_chart_amp1 <- injury %>% select(Amputation)
table(pie_chart_amp1)
pie_chart_amp2 <- c(33173,11997)
pie(pie_chart_amp2, radius=1, labels=c("Non-Amputation 73.4%","Amputation 26.6%"), col=c("#BFFF00","#FF0000"), main="Amputation Rate in All Injuries")
```

```{r}
state_hos_rate1 <- injury %>% group_by(State) %>% filter(Hospitalized==1) %>% summarise(number1 = n())
state_hos_rate2 <- injury %>% group_by(State) %>% filter(Hospitalized!=2,3,4,9) %>% summarise(number2 = n())
pie_chart_state1 <- merge(injury_state,state_hos_rate1)
pie_chart_state2 <- merge(pie_chart_state1, state_hos_rate2)
pie_chart_state3 <- mutate(pie_chart_state2, hos_rate=(number1/number2))
```

```{r}
state_amp_rate1 <- injury %>% group_by(State) %>% filter(Amputation==1) %>% summarise(number3 = n())
state_amp_rate2 <- injury %>% group_by(State) %>% filter(Amputation!=2,3,4,9) %>% summarise(number4 = n())
pie_chart_state4 <- merge(pie_chart_state3,state_amp_rate1)
pie_chart_state5 <- merge(pie_chart_state4,state_amp_rate2)
pie_chart_state6 <- mutate(pie_chart_state5, amp_rate=(number3/number4))
```
```{r}
ggplot(data = pie_chart_state6, aes(x = hos_rate, y = amp_rate, label = State)) +　labs(title = "Relationship betweem Hospitalization and Amputation Rates according to States ", x = "Hospitalization Rate", y = "Amputation Rate") + geom_point()
```