---
title: "BST260fial"
author: "Keiko"
date: "11/29/2019"
output: html_document
---

read datafile 
```{r setup, include=FALSE}
library(tidyverse)
library(readr)
data <- read_delim("injurydata.csv",";", escape_double = FALSE, trim_ws = TRUE)
```

cアンプタ+/-の距離の箱ひげ図
```{r}
library(ggplot2)
data$AMPUTATION
data$HOSPITALIZED
data[c(168,169,170,331,332,333,436,437,438),]
data[c(436,437,438),]
nrow(data)
```


```{r}
data1<- data %>%
filter(data$ZIP<99999)
nrow(data1)

data2<-data1 %>%
filter(data1$ZIP>1000) 
dat
```



```{r}
summary(data2$AMPUTATION)
hist(data2$AMPUTATION)

```

```{r}

data3 <- data2 %>% filter(AMPUTATION==c("0","1")) 
nrow(data3)
data4 <- data3 %>% filter(NEAR_DIST<10^6)
nrow(data4)

hist(dat_2$NEAR_DIST)
summary(dat_2$NEAR_DIST)

dat_2 %>%
  ggplot(aes(group=AMPUTATION,y=log10(NEAR_DIST)))+
  geom_boxplot()+
  xlab("amputation")+
  ylab("distance from hospital log10")

summary(dat$NEAR_DIST)
```

```{r}
dataa <- data %>% filter(HOSPITALIZED<2)
datas <- dataa %>% filter(HOSPITALIZED>-1)
datad <- datas %>% filter(AMPUTATION<2)
dataf <- datad %>% filter(AMPUTATION>-1)
dataq <- dataf %>% filter(NEAR_FID>0)

hist(dataf$NEAR_DIST)
summary(dataf$NEAR_DIST)

datag <- dataq %>% filter(NEAR_DIST<10^6)
```


boxplot
```{r}
datag$AMPUTATION <- as.factor(datag$AMPUTATION)
datag %>%
  ggplot(aes(x=AMPUTATION,y=log10(NEAR_DIST)))+
  geom_boxplot()+
  xlab("amputation")+
  ylab("distance from hospital log10")

```



density graph
```{r}
datag %>% ggplot(aes(log10(NEAR_DIST), fill=AMPUTATION)) + geom_density(alpha = 0.2)+
  xlab("distance to hospital, log10, meter")
```

ttest
```{r}
t.test(datag$NEAR_DIST~datag$AMPUTATION)
```



### regression


detecting mutiple injury
```{r}
Left<-function(x,chr){
    return(substr(x,1,chr))}

datag<-mutate(datag, leftMul = Left(PARTOFBODYTITLE,3))

datag<-mutate(datag, MultiInj = ifelse(datag$leftMul=="Mul", "1", "0"))
head(datag)

```


cRegression　(age, distance, hospitalization, multiple injury+/-)
```{r}
fit <- glm(AMPUTATION ~ NEAR_DIST  + HOSPITALIZED + MultiInj, data = datag, family = "binomial")
summary(fit)
```


```{r}
datag %>% ggplot(x=MultiInj, y=AMPUTATION)+
  geom_col()
```

