---
title: "keitaro_final"
author: "Keitaro Mahara"
date: "12/5/2019"
output: html_document
---

---
title: "keitaro_260final"
author: "Keitaro Mahara"
date: "12/5/2019"
output: html_document
---

```{r data extraction}
library(tidyverse)
library(readr)
#data <- read_delim("injurydata.csv",";", escape_double = FALSE, trim_ws = TRUE)

source("data_source.R")
```



```{r amputaion and distance}

res <- t.test(NEAR_DIST ~ AMPUTATION, data = data)
res$p.value
res$estimate

data_bar <- data %>% group_by(AMPUTATION) %>%
  summarise(mean = mean(NEAR_DIST), sd =sd(NEAR_DIST), se = sd(NEAR_DIST)/sqrt(n())) 
data_bar 

data_bar %>%
  ggplot(aes(x = as.factor(AMPUTATION), y = mean)) +
  geom_bar(stat = "identity")+
  geom_errorbar(aes(ymin=mean - se, ymax= mean +se)) +
  xlab("amputation")+
  ylab("distance from hospital")

summary(lm(AMPUTATION ~ NEAR_DIST, data=data))


```




```{r distance and states, echo=FALSE}

data_bar_s <- data %>% group_by(STATE) %>%
  summarise(mean = mean(NEAR_DIST), sd =sd(NEAR_DIST), se = sd(NEAR_DIST)/sqrt(n())) 
data_bar_s
class(data_bar)
class(data_bar$mean)

data_bar_s %>% mutate(STATE = reorder(STATE, mean)) %>%
  ggplot(aes(x = STATE, y = mean)) +
  geom_bar(stat = "identity")+
  geom_errorbar(aes(ymin=mean - se, ymax= mean +se)) +
  xlab("State")+
  ylab("distance from hospital") +
   coord_flip() 

```


```{r amputation rate and distance by state}

data_amputation_rate <- data %>% group_by(STATE) %>%
  summarise(mean = mean(NEAR_DIST), sd =sd(NEAR_DIST), se = sd(NEAR_DIST)/sqrt(n()),amputation_rate = mean(AMPUTATION), amputation =sum(AMPUTATION)) %>% 
  filter(amputation >= 10)

# manipulate data for the map
data_amputation_rate_1 <- data_amputation_rate %>%
  mutate(region = str_to_lower(STATE))

library(maps)
states_map <- map_data("state")
amputation_map <- left_join(states_map, data_amputation_rate_1, by = "region")


# Create the map
amputation_map %>%
ggplot(aes(long, lat, group = group))+
  geom_polygon(aes(fill = amputation_rate), color = "gray90")+
  scale_fill_gradient(low = "white", high = "#CB454A") +
  labs(title = "Amputation rate")

library(ggthemes)
amputation_map %>%
ggplot(mapping = aes(long, lat, group = group,fill = amputation_rate))+
  geom_polygon(color = "black", size = 0.1) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(title = "Amputation rate") + 
  theme_map() +
  scale_fill_gradient(low = "white", high = "#CB454A") 




data_amputation_rate %>% 
  ggplot(aes(x = mean, y = amputation_rate, label = STATE, size = amputation)) +
  geom_point()+
  xlab("Distance from hospital")+
  ylab("Amputation rate")

data_amputation_rate %>% 
  ggplot(aes(x = mean, y = amputation_rate, label = STATE, size = amputation)) +
  geom_point()+
  geom_text(hjust = -0.2, nudge_x = 0.05, size = 3) +
  xlab("Distance from hospital")+
  ylab("Amputation rate")


library(openintro)
library(ggrepel)

data_amputation_rate %>% mutate(abb = state2abbr(STATE)) %>%
  ggplot(aes(x = mean, y = amputation_rate, label = abb, size = amputation)) +
  geom_point()+
  geom_text(hjust = -0.2, nudge_x = 0.05, size = 3) +
  xlab("Distance from hospital")+
  ylab("Amputation rate") +
  xlim(0,15000)

data_amputation_rate %>% mutate(abb = state2abbr(STATE)) %>%
  ggplot(aes(x = mean, y = amputation_rate, label = abb, size = amputation)) +
  geom_point()+
  geom_text_repel(size =3) +
  xlab("Distance from hospital")+
  ylab("Amputation rate") +
  xlim(0,15000)

data_amputation_rate %>% 
  ggplot(aes(x = mean, y = amputation_rate, label = STATE,size = amputation)) +
  geom_point()+
  geom_smooth(method="lm") +
  xlab("Distance from hospital")+
  ylab("Amputation rate") +
  xlim(0,15000)

cor.test(data_amputation_rate$mean, data_amputation_rate$amputation_rate)

```

```{r}
library(maps)
library(ggthemes)

us_map <- ggplot()+
  geom_polygon(data = states_map, aes(long, lat, group = group), color = "black", size = 0.1, fill = "white") +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  theme_map() 
us_map

class(data$LATITUDE)
data_map <- data %>% mutate(LONGITUDE = as.numeric(LONGITUDE), LATITUDE =as.numeric(LATITUDE), AMPUTATION = as.factor(AMPUTATION)) %>% filter(LATITUDE > 20 & LATITUDE < 50 & LONGITUDE > -120)
us_map + geom_point(data = data_map, aes(x=LONGITUDE, y=LATITUDE, color = AMPUTATION), size=0.0001)

```

