---
title: "OGAWA"
output: html_document
---

read injury datafile 
```{r setup, include=FALSE}
library(tidyverse)
library(readr)
data <- read_delim("injurydata.csv",";", escape_double = FALSE, trim_ws = TRUE)
```

read census data
```{r}
d_census <- read_csv("ACS_16_5YR_S1811_with_ann.csv")
a <-read_csv("ACS_17_5YR_S0101_with_ann.csv")
b  <-read_csv("ACS_17_5YR_S0701_with_ann.csv")
c <-read_csv("ACS_17_5YR_S0801_with_ann.csv")
d <-read_csv("ACS_17_5YR_S1101_with_ann.csv")
e <-read_csv("ACS_17_5YR_S1901_with_ann.csv")
f <-read_csv("ACS_17_5YR_S2301_with_ann.csv")

a<-a %>%   rename('ZIP' = 'GEO.id2')
b<-b %>%   rename('ZIP' = 'GEO.id2')
c<-c %>%   rename('ZIP' = 'GEO.id2')
d<-d %>%   rename('ZIP' = 'GEO.id2')
e<-e %>%   rename('ZIP' = 'GEO.id2')

data <- data %>% left_join(a,by="ZIP")
data <- data %>% left_join(b,by="ZIP")
data <- data %>% left_join(c,by="ZIP")
data <- data %>% left_join(d,by="ZIP")
data <- data %>% left_join(e,by="ZIP")
```

data merge
```{r}
d_census <- d_census %>%   rename('ZIP' = 'GEO.id2')
d_census$ZIP <- as.numeric(d_census$ZIP)

data$ZIP <- as.numeric(data$ZIP)
data <- data %>% left_join(d_census)
?join

data%>%group_by(ZIP)%>%count()

table(data$GEO.id)
table(d_census$GEO.id)
```


Employer name
```{r}
data$EMPLOYER =gsub(".*usps|us postal|united states postal|u.s. postal|u.s postal|u. s postal|u. s. postal.*","US_Postal_Service",                   ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*US_Postal_Service.*","USPS", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*united parcel|ups |ups,.*","United_Parcel_Service", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*United_Parcel_Service.*","UPS", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*american airl.*","American Airlines", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*AT &|AT&.*","AT_T", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*AT_T.*","AT&T Inc", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*walmart|wallmart|wal-mart.*","wal_mart", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*wal_mart.*","Walmart", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Publix.*","Publix_", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Publix_.*","Publix", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Asplundh.*","Asplundh_", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Asplundh_.*","Asplundh", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*sodexo.*","sodexo_", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*sodexo_.*","Sodexo", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Waste Management.*","Waste_Management", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Waste_Management.*","Waste Management", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Tyson Foods.*","Tyson_Foods", ignore.case = TRUE, data$EMPLOYER)
data$EMPLOYER =gsub(".*Tyson_Foods.*","Tyson Foods", ignore.case = TRUE, data$EMPLOYER)
  
```



Label name
```{r}
library(papeR)
labels(d_census)<- c("id","Zip",
"Geography",
"Total Civilian Noninstitutionalized Population; Estimate; Population Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Margin of Error; Population Age 16 and Over",
"With a Disability; Estimate; Population Age 16 and Over",
"With a Disability; Margin of Error; Population Age 16 and Over",
"No Disability; Estimate; Population Age 16 and Over",
"No Disability; Margin of Error; Population Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Estimate; EMPLOYMENT STATUS - Employed",
"Total Civilian Noninstitutionalized Population; Margin of Error; EMPLOYMENT STATUS - Employed",
"With a Disability; Estimate; EMPLOYMENT STATUS - Employed",
"With a Disability; Margin of Error; EMPLOYMENT STATUS - Employed",
"No Disability; Estimate; EMPLOYMENT STATUS - Employed",
"No Disability; Margin of Error; EMPLOYMENT STATUS - Employed",
"Total Civilian Noninstitutionalized Population; Estimate; EMPLOYMENT STATUS - Not in Labor Force",
"Total Civilian Noninstitutionalized Population; Margin of Error; EMPLOYMENT STATUS - Not in Labor Force",
"With a Disability; Estimate; EMPLOYMENT STATUS - Not in Labor Force",
"With a Disability; Margin of Error; EMPLOYMENT STATUS - Not in Labor Force",
"No Disability; Estimate; EMPLOYMENT STATUS - Not in Labor Force",
"No Disability; Margin of Error; EMPLOYMENT STATUS - Not in Labor Force",
"Total Civilian Noninstitutionalized Population; Estimate; Employed Population Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Margin of Error; Employed Population Age 16 and Over",
"With a Disability; Estimate; Employed Population Age 16 and Over",
"With a Disability; Margin of Error; Employed Population Age 16 and Over",
"No Disability; Estimate; Employed Population Age 16 and Over",
"No Disability; Margin of Error; Employed Population Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Private for-profit wage and salary workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Private for-profit wage and salary workers",
"With a Disability; Estimate; CLASS OF WORKER - Private for-profit wage and salary workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Private for-profit wage and salary workers",
"No Disability; Estimate; CLASS OF WORKER - Private for-profit wage and salary workers",
"No Disability; Margin of Error; CLASS OF WORKER - Private for-profit wage and salary workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Employee of private company workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Employee of private company workers",
"With a Disability; Estimate; CLASS OF WORKER - Employee of private company workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Employee of private company workers",
"No Disability; Estimate; CLASS OF WORKER - Employee of private company workers",
"No Disability; Margin of Error; CLASS OF WORKER - Employee of private company workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Self-employed in own incorporated business workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Self-employed in own incorporated business workers",
"With a Disability; Estimate; CLASS OF WORKER - Self-employed in own incorporated business workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Self-employed in own incorporated business workers",
"No Disability; Estimate; CLASS OF WORKER - Self-employed in own incorporated business workers",
"No Disability; Margin of Error; CLASS OF WORKER - Self-employed in own incorporated business workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"With a Disability; Estimate; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"No Disability; Estimate; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"No Disability; Margin of Error; CLASS OF WORKER - Private not-for-profit wage and salary workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Local government workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Local government workers",
"With a Disability; Estimate; CLASS OF WORKER - Local government workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Local government workers",
"No Disability; Estimate; CLASS OF WORKER - Local government workers",
"No Disability; Margin of Error; CLASS OF WORKER - Local government workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - State government workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - State government workers",
"With a Disability; Estimate; CLASS OF WORKER - State government workers",
"With a Disability; Margin of Error; CLASS OF WORKER - State government workers",
"No Disability; Estimate; CLASS OF WORKER - State government workers",
"No Disability; Margin of Error; CLASS OF WORKER - State government workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Federal government workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Federal government workers",
"With a Disability; Estimate; CLASS OF WORKER - Federal government workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Federal government workers",
"No Disability; Estimate; CLASS OF WORKER - Federal government workers",
"No Disability; Margin of Error; CLASS OF WORKER - Federal government workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"With a Disability; Estimate; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"No Disability; Estimate; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"No Disability; Margin of Error; CLASS OF WORKER - Self-employed in own not incorporated business workers",
"Total Civilian Noninstitutionalized Population; Estimate; CLASS OF WORKER - Unpaid family workers",
"Total Civilian Noninstitutionalized Population; Margin of Error; CLASS OF WORKER - Unpaid family workers",
"With a Disability; Estimate; CLASS OF WORKER - Unpaid family workers",
"With a Disability; Margin of Error; CLASS OF WORKER - Unpaid family workers",
"No Disability; Estimate; CLASS OF WORKER - Unpaid family workers",
"No Disability; Margin of Error; CLASS OF WORKER - Unpaid family workers",
"Total Civilian Noninstitutionalized Population; Estimate; OCCUPATION - Management, business, science, and arts occupations",
"Total Civilian Noninstitutionalized Population; Margin of Error; OCCUPATION - Management, business, science, and arts occupations",
"With a Disability; Estimate; OCCUPATION - Management, business, science, and arts occupations",
"With a Disability; Margin of Error; OCCUPATION - Management, business, science, and arts occupations",
"No Disability; Estimate; OCCUPATION - Management, business, science, and arts occupations",
"No Disability; Margin of Error; OCCUPATION - Management, business, science, and arts occupations",
"Total Civilian Noninstitutionalized Population; Estimate; OCCUPATION - Service occupations",
"Total Civilian Noninstitutionalized Population; Margin of Error; OCCUPATION - Service occupations",
"With a Disability; Estimate; OCCUPATION - Service occupations",
"With a Disability; Margin of Error; OCCUPATION - Service occupations",
"No Disability; Estimate; OCCUPATION - Service occupations",
"No Disability; Margin of Error; OCCUPATION - Service occupations",
"Total Civilian Noninstitutionalized Population; Estimate; OCCUPATION - Sales and office occupations",
"Total Civilian Noninstitutionalized Population; Margin of Error; OCCUPATION - Sales and office occupations",
"With a Disability; Estimate; OCCUPATION - Sales and office occupations",
"With a Disability; Margin of Error; OCCUPATION - Sales and office occupations",
"No Disability; Estimate; OCCUPATION - Sales and office occupations",
"No Disability; Margin of Error; OCCUPATION - Sales and office occupations",
"Total Civilian Noninstitutionalized Population; Estimate; OCCUPATION - Natural resources, construction, and maintenance occupations",
"Total Civilian Noninstitutionalized Population; Margin of Error; OCCUPATION - Natural resources, construction, and maintenance occupations",
"With a Disability; Estimate; OCCUPATION - Natural resources, construction, and maintenance occupations",
"With a Disability; Margin of Error; OCCUPATION - Natural resources, construction, and maintenance occupations",
"No Disability; Estimate; OCCUPATION - Natural resources, construction, and maintenance occupations",
"No Disability; Margin of Error; OCCUPATION - Natural resources, construction, and maintenance occupations",
"Total Civilian Noninstitutionalized Population; Estimate; OCCUPATION - Production, transportation, and material moving occupations",
"Total Civilian Noninstitutionalized Population; Margin of Error; OCCUPATION - Production, transportation, and material moving occupations",
"With a Disability; Estimate; OCCUPATION - Production, transportation, and material moving occupations",
"With a Disability; Margin of Error; OCCUPATION - Production, transportation, and material moving occupations",
"No Disability; Estimate; OCCUPATION - Production, transportation, and material moving occupations",
"No Disability; Margin of Error; OCCUPATION - Production, transportation, and material moving occupations",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"With a Disability; Estimate; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"With a Disability; Margin of Error; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"No Disability; Estimate; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"No Disability; Margin of Error; INDUSTRY - Agriculture, forestry, fishing and hunting, and mining",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Construction",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Construction",
"With a Disability; Estimate; INDUSTRY - Construction",
"With a Disability; Margin of Error; INDUSTRY - Construction",
"No Disability; Estimate; INDUSTRY - Construction",
"No Disability; Margin of Error; INDUSTRY - Construction",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Manufacturing",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Manufacturing",
"With a Disability; Estimate; INDUSTRY - Manufacturing",
"With a Disability; Margin of Error; INDUSTRY - Manufacturing",
"No Disability; Estimate; INDUSTRY - Manufacturing",
"No Disability; Margin of Error; INDUSTRY - Manufacturing",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Wholesale trade",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Wholesale trade",
"With a Disability; Estimate; INDUSTRY - Wholesale trade",
"With a Disability; Margin of Error; INDUSTRY - Wholesale trade",
"No Disability; Estimate; INDUSTRY - Wholesale trade",
"No Disability; Margin of Error; INDUSTRY - Wholesale trade",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Retail trade",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Retail trade",
"With a Disability; Estimate; INDUSTRY - Retail trade",
"With a Disability; Margin of Error; INDUSTRY - Retail trade",
"No Disability; Estimate; INDUSTRY - Retail trade",
"No Disability; Margin of Error; INDUSTRY - Retail trade",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Transportation and warehousing, and utilities",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Transportation and warehousing, and utilities",
"With a Disability; Estimate; INDUSTRY - Transportation and warehousing, and utilities",
"With a Disability; Margin of Error; INDUSTRY - Transportation and warehousing, and utilities",
"No Disability; Estimate; INDUSTRY - Transportation and warehousing, and utilities",
"No Disability; Margin of Error; INDUSTRY - Transportation and warehousing, and utilities",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Information",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Information",
"With a Disability; Estimate; INDUSTRY - Information",
"With a Disability; Margin of Error; INDUSTRY - Information",
"No Disability; Estimate; INDUSTRY - Information",
"No Disability; Margin of Error; INDUSTRY - Information",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"With a Disability; Estimate; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"With a Disability; Margin of Error; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"No Disability; Estimate; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"No Disability; Margin of Error; INDUSTRY - Finance and insurance, and real estate and rental and leasing",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"With a Disability; Estimate; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"With a Disability; Margin of Error; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"No Disability; Estimate; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"No Disability; Margin of Error; INDUSTRY - Professional, scientific, and management, and administrative and waste management services",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Educational services, and health care and social assistance",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Educational services, and health care and social assistance",
"With a Disability; Estimate; INDUSTRY - Educational services, and health care and social assistance",
"With a Disability; Margin of Error; INDUSTRY - Educational services, and health care and social assistance",
"No Disability; Estimate; INDUSTRY - Educational services, and health care and social assistance",
"No Disability; Margin of Error; INDUSTRY - Educational services, and health care and social assistance",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"With a Disability; Estimate; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"With a Disability; Margin of Error; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"No Disability; Estimate; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"No Disability; Margin of Error; INDUSTRY - Arts, entertainment, and recreation, and accommodation and food services",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Other services (except public administration)",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Other services (except public administration)",
"With a Disability; Estimate; INDUSTRY - Other services (except public administration)",
"With a Disability; Margin of Error; INDUSTRY - Other services (except public administration)",
"No Disability; Estimate; INDUSTRY - Other services (except public administration)",
"No Disability; Margin of Error; INDUSTRY - Other services (except public administration)",
"Total Civilian Noninstitutionalized Population; Estimate; INDUSTRY - Public administration",
"Total Civilian Noninstitutionalized Population; Margin of Error; INDUSTRY - Public administration",
"With a Disability; Estimate; INDUSTRY - Public administration",
"With a Disability; Margin of Error; INDUSTRY - Public administration",
"No Disability; Estimate; INDUSTRY - Public administration",
"No Disability; Margin of Error; INDUSTRY - Public administration",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - drove alone",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Car, truck, or van - carpooled",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Public transportation (excluding taxicab)",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Walked",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Taxicab, motorcycle, bicycle, or other means",
"Total Civilian Noninstitutionalized Population; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"Total Civilian Noninstitutionalized Population; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"With a Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"With a Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"No Disability; Estimate; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"No Disability; Margin of Error; COMMUTING TO WORK - Workers Age 16 and Over - Worked at home",
"Total Civilian Noninstitutionalized Population; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"Total Civilian Noninstitutionalized Population; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"With a Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"With a Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"No Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"No Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over",
"Total Civilian Noninstitutionalized Population; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"Total Civilian Noninstitutionalized Population; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"With a Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"With a Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"No Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"No Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Less than high school graduate",
"Total Civilian Noninstitutionalized Population; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"Total Civilian Noninstitutionalized Population; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"With a Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"With a Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"No Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"No Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - High school graduate (includes equivalency)",
"Total Civilian Noninstitutionalized Population; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"Total Civilian Noninstitutionalized Population; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"With a Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"With a Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"No Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"No Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Some college or associate's degree",
"Total Civilian Noninstitutionalized Population; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"Total Civilian Noninstitutionalized Population; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"With a Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"With a Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"No Disability; Estimate; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"No Disability; Margin of Error; EDUCATIONAL ATTAINMENT - Population Age 25 and Over - Bachelor's degree or higher",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $1 to $4,999 or loss",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $5,000 to $14,999",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $15,000 to $24,999",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $25,000 to $34,999",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $35,000 to $49,999",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $50,000 to $74,999",
"Total Civilian Noninstitutionalized Population; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"Total Civilian Noninstitutionalized Population; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"With a Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"With a Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"No Disability; Estimate; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"No Disability; Margin of Error; EARNINGS IN PAST 12 MONTHS (IN 2016 INFLATION ADJUSTED DOLLARS) - Population Age 16 and over with earnings - $75,000 or more",
"Total Civilian Noninstitutionalized Population; Estimate; Median Earnings",
"Total Civilian Noninstitutionalized Population; Margin of Error; Median Earnings",
"With a Disability; Estimate; Median Earnings",
"With a Disability; Margin of Error; Median Earnings",
"No Disability; Estimate; Median Earnings",
"No Disability; Margin of Error; Median Earnings",
"Total Civilian Noninstitutionalized Population; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"Total Civilian Noninstitutionalized Population; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"With a Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"With a Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"No Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"No Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined",
"Total Civilian Noninstitutionalized Population; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"Total Civilian Noninstitutionalized Population; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"With a Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"With a Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"No Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"No Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - Below 100 percent of the poverty level",
"Total Civilian Noninstitutionalized Population; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"Total Civilian Noninstitutionalized Population; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"With a Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"With a Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"No Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"No Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - 100 to 149 percent of the poverty level",
"Total Civilian Noninstitutionalized Population; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level",
"Total Civilian Noninstitutionalized Population; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level",
"With a Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level",
"With a Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level",
"No Disability; Estimate; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level",
"No Disability; Margin of Error; POVERTY STATUS IN THE PAST 12 MONTHS - Population Age 16 and over for whom poverty status is determined - At or above 150 percent of the poverty level","Zip code"
)
labels(d_census)
```